"""Feature availability matrix for Forecast Data Contract V1."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List

from modules.forecast_research.contract import CONTRACT_VERSION, EXPECTED_UNIVERSE_SIZE

REPO_ROOT = Path(__file__).resolve().parents[2]


def build_feature_availability_matrix() -> Dict[str, Any]:
    rows: List[Dict[str, Any]] = [
        {
            "feature": "market_real",
            "existing_source": "market_daily_t0 / earning_money_snapshots / t0_freeze",
            "available_now": True,
            "historical_start": "2026-07-31 (full board); 2026-08-13 (MDT0)",
            "pit_safe": True,
            "complete_142": True,
            "stored_daily": "when Streamlit EOD path runs",
            "needs_new_collection": False,
            "forward_only": False,
            "retention": "reuse existing + forecast_t0_daily derived",
        },
        {
            "feature": "market_live",
            "existing_source": "market_daily_t0 / earning_money_snapshots",
            "available_now": True,
            "historical_start": "2026-07-31 / 2026-08-13",
            "pit_safe": True,
            "complete_142": True,
            "stored_daily": "when Streamlit EOD path runs",
            "needs_new_collection": False,
            "forward_only": False,
            "retention": "reuse existing",
        },
        {
            "feature": "market_forecast_continuation",
            "existing_source": "calc_market_forecast → MDT0 / EMS",
            "available_now": True,
            "historical_start": "2026-07-31",
            "pit_safe": True,
            "complete_142": True,
            "stored_daily": "yes (via existing writers)",
            "needs_new_collection": False,
            "forward_only": False,
            "retention": "reuse + derive trajectories in forecast_t0",
        },
        {
            "feature": "fc_d1/d3/d5 + accel",
            "existing_source": "derived in forecast_t0 from prior frozen T0",
            "available_now": True,
            "historical_start": "after ≥2–6 COMPLETE T0 rows",
            "pit_safe": True,
            "complete_142": "depends on T0 completeness",
            "stored_daily": "derived layer",
            "needs_new_collection": False,
            "forward_only": False,
            "retention": "forecast_t0_daily.csv",
        },
        {
            "feature": "group counts/shares (8 groups)",
            "existing_source": "EMS board + MDT0 aggregates",
            "available_now": True,
            "historical_start": "2026-07-31",
            "pit_safe": True,
            "complete_142": True,
            "stored_daily": "EMS yes; MDT0 partial date span",
            "needs_new_collection": False,
            "forward_only": False,
            "retention": "reuse EMS raw + forecast_t0 derived",
        },
        {
            "feature": "RSI40/50/60 breadth",
            "existing_source": "derivable from EMS rsi14; MDT0 breadth ladder",
            "available_now": True,
            "historical_start": "2026-07-31",
            "pit_safe": True,
            "complete_142": True,
            "stored_daily": "derived / MDT0",
            "needs_new_collection": False,
            "forward_only": False,
            "retention": "forecast_t0 derived",
        },
        {
            "feature": "OBV / slope breadth",
            "existing_source": "EMS obv_status + ema9_ma20_slope; MDT0 pct",
            "available_now": True,
            "historical_start": "2026-07-31",
            "pit_safe": True,
            "complete_142": True,
            "stored_daily": "yes",
            "needs_new_collection": False,
            "forward_only": False,
            "retention": "reuse",
        },
        {
            "feature": "near_low20/60, near_high20",
            "existing_source": "EMS near_bottom_* / dist_high20_pct",
            "available_now": True,
            "historical_start": "2026-07-31",
            "pit_safe": True,
            "complete_142": True,
            "stored_daily": "EMS",
            "needs_new_collection": False,
            "forward_only": False,
            "retention": "reuse EMS raw",
        },
        {
            "feature": "leadership concentration top10",
            "existing_source": "derived from EMS rs5",
            "available_now": True,
            "historical_start": "2026-07-31",
            "pit_safe": True,
            "complete_142": True,
            "stored_daily": "derived in forecast_t0",
            "needs_new_collection": False,
            "forward_only": False,
            "retention": "forecast_t0",
        },
        {
            "feature": "VNINDEX OHLCV",
            "existing_source": "market_daily_t0",
            "available_now": True,
            "historical_start": "2026-08-13",
            "pit_safe": True,
            "complete_142": "n/a (index)",
            "stored_daily": "when MDT0 freezes (≥18:00 VN via Streamlit)",
            "needs_new_collection": False,
            "forward_only": False,
            "retention": "reuse MDT0",
        },
        {
            "feature": "VNINDEX technicals (RSI/MACD/BB)",
            "existing_source": "schema reserved in MDT0; values empty",
            "available_now": False,
            "historical_start": None,
            "pit_safe": "if filled at freeze time",
            "complete_142": "n/a",
            "stored_daily": False,
            "needs_new_collection": True,
            "forward_only": True,
            "retention": "fill existing MDT0 columns prospectively",
        },
        {
            "feature": "sector participation",
            "existing_source": "t0_observation_freeze / EL pattern_history have sector; EMS lacks sector",
            "available_now": "partial",
            "historical_start": "2026-08-13 freeze",
            "pit_safe": True,
            "complete_142": True,
            "stored_daily": "freeze/EL yes; EMS no",
            "needs_new_collection": "optional EMS sector column",
            "forward_only": False,
            "retention": "reuse freeze; optional EMS enrichment",
        },
        {
            "feature": "foreign net flow",
            "existing_source": "NONE",
            "available_now": False,
            "historical_start": None,
            "pit_safe": "n/a",
            "complete_142": "n/a",
            "stored_daily": False,
            "needs_new_collection": True,
            "forward_only": True,
            "retention": "P0 prospective collector",
        },
        {
            "feature": "market turnover / ADV",
            "existing_source": "partial via VNINDEX volume; no ADV series",
            "available_now": "partial",
            "historical_start": "2026-08-13 VNI volume",
            "pit_safe": True,
            "complete_142": "n/a",
            "stored_daily": "MDT0 volume",
            "needs_new_collection": True,
            "forward_only": True,
            "retention": "P0 ADV/turnover series",
        },
        {
            "feature": "T3/T5/T10 Forecast outcomes",
            "existing_source": "NEW forecast_outcomes.csv (derived from EMS/VNI)",
            "available_now": True,
            "historical_start": "matures from existing EMS dates",
            "pit_safe": "labels after maturity only",
            "complete_142": "uses EMS session calendar",
            "stored_daily": "maturity job",
            "needs_new_collection": False,
            "forward_only": False,
            "retention": "separate outcome layer forever",
        },
        {
            "feature": "Camera 5m OHLCV",
            "existing_source": "modules/intraday_memory parquet",
            "available_now": True,
            "historical_start": "VPS collect retention",
            "pit_safe": True,
            "complete_142": "intended",
            "stored_daily": "systemd collect",
            "needs_new_collection": False,
            "forward_only": False,
            "retention": "keep raw partitions (no purge in code)",
        },
    ]
    return {
        "contract_version": CONTRACT_VERSION,
        "expected_universe_size": EXPECTED_UNIVERSE_SIZE,
        "rows": rows,
    }


def write_feature_matrix(path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = build_feature_availability_matrix()
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    return path
