"""LIVE CANDIDATE V2 Action Layer — SHADOW ONLY.

Brain A = WHAT. Camera/P×V = WHEN. This layer is shadow confirmation of WHEN.
It is not authority to spend capital. BUY_READY here is a research state only.

Production trading permissions stay FALSE:
  candidate_is_buy = False
  pxv_implies_buy = False
  alert_eligible = False
"""

from __future__ import annotations

from modules.intraday_pxv_v1.constants import (
    OVERLAY_TRUTH_CANONICAL,
    OVERLAY_TRUTH_RETROSPECTIVE,
)
from modules.live_candidate_v2_nomination.contract import (
    MARKET_PERMISSION_OK,
    PRIMARY_SETUPS,
    SECONDARY_SETUP,
    STATUS_NOMINATED,
)
from modules.live_candidate_v2_nomination.intent import REF_BREAKOUT, REF_EMA9

SCHEMA_EVIDENCE = "live_candidate_v2_action_evidence.v1"
SCHEMA_STATE = "live_candidate_v2_action_state.v1"
SLICE = "shadow_action_v1"
MODE = "SHADOW_ONLY"

# Production BUY permissions — hard false for this slice.
CANDIDATE_IS_BUY = False
PXV_IMPLIES_BUY = False
ALERT_ELIGIBLE = False

STATE_NOMINATED = STATUS_NOMINATED
STATE_WAIT = "WAIT"
STATE_BUY_READY = "BUY_READY"
STATE_WEAKENED = "WEAKENED"
STATE_NO_OBSERVATION = "NO_OBSERVATION"

SHADOW_ACTION_STATES = frozenset(
    {
        STATE_NOMINATED,
        STATE_WAIT,
        STATE_BUY_READY,
        STATE_WEAKENED,
        STATE_NO_OBSERVATION,
    }
)

ROUTE_PULL = frozenset({"PULL ĐẸP", "PULL VỪA"})
ROUTE_MANH = "CP MẠNH"
ROUTE_BREAK = "MUA BREAK"
ROUTE_EARLY = SECONDARY_SETUP
PRIMARY_ACTION_SETUPS = PRIMARY_SETUPS

QUIET_VOLUME = frozenset({"CONTRACTION", "NORMAL"})
# Quiet-supply evidence inside a pull. NORMAL may confirm a hold; it is not
# itself evidence that supply dried up.
PULL_SUPPLY_VOLUME = "CONTRACTION"
# Last N legal completed bars ending at the second reclaim bar.
# The final two are the confirmation pair and do not count as prior pull
# evidence, so a qualifying contraction can sit at most 4 completed bars
# before that pair. Count is legal bars, not wall-clock minutes.
PULL_EVIDENCE_WINDOW_BARS = 6

# close_vs_ref_pct at or under this is the frozen EMA9 area (every close
# below the ref is included). 1.0 is the existing daily PULL ĐẸP distance
# band from classify_pull_label, read here off the frozen 5m comparison.
# Not a new indicator.
PULL_ZONE_MAX_PCT = 1.0

# EARLY reads FAM_EXPANSION["value"] (bar volume / median of up to
# RESEARCH_DEFAULT_SESSION_MEDIAN_BARS prior same-session bars).
# Improvement is strictly above that median. The ceiling is the existing
# breakout multiple RESEARCH_DEFAULT_EXPANSION_X (2.0), exclusive, so a
# 2.0× spike stays a BREAK/MẠNH event and cannot qualify EARLY.
# Price progress uses the same 1.0% EMA9 band: above the frozen EMA9, and
# not an extension beyond that band.
EARLY_MODERATE_VOLUME_MIN = 1.0
EARLY_MAX_PROGRESS_PCT = PULL_ZONE_MAX_PCT

DEFAULT_ARTIFACT_RELPATH = "research/live_candidate_v2_action"
EVIDENCE_NAME = "v2_action_evidence.jsonl"
STATE_NAME = "v2_action_state.json"
EMITTED_NAME = "v2_action_emitted_keys.json"
ENV_ACTION_OUT = "MRBOT_V2_ACTION_OUT"
ENV_V2_SIDECAR = "MRBOT_V2_CAMERA_SIDECAR"
ENV_V2_SIDECAR_SOURCE = "MRBOT_V2_SIDECAR_SOURCE"

WAITING_FOR_NEXT_LIVE_ELIGIBLE_5M = "WAITING_FOR_NEXT_LIVE_ELIGIBLE_5M"

# Machine-readable transition reasons. Stable for replay/tests.
REASON_NO_OBSERVATION_CAP = "NO_OBSERVATION_CAP"
REASON_NO_OBSERVATION_NO_DATA = "NO_OBSERVATION_NO_DATA"
REASON_NO_OBSERVATION_MISSING_CAMERA = "NO_OBSERVATION_MISSING_CAMERA"
REASON_NO_OBSERVATION_PROVIDER = "NO_OBSERVATION_PROVIDER"
REASON_EARLY_NO_FROZEN_REF = "EARLY_NO_DEFENSIBLE_FROZEN_REF"
REASON_EARLY_EVIDENCE_ONLY = "EARLY_EVIDENCE_ONLY_NO_BUY_READY"
REASON_PULL_SINGLE_BAR = "PULL_SINGLE_BAR_RECLAIM"
REASON_PULL_BELOW_REF = "PULL_BELOW_REF"
REASON_PULL_BUY_READY = "PULL_TWO_BAR_RECLAIM_QUIET_VOLUME"
REASON_PULL_FAM_SELL = "PULL_FAM_SELL_ON_CONFIRMATION"
REASON_PULL_VOLUME_NOT_QUIET = "PULL_VOLUME_NOT_QUIET"
REASON_PULL_NO_QUIET_SUPPLY = "PULL_NO_QUIET_SUPPLY_BEFORE_RECLAIM"
REASON_EARLY_SINGLE_BAR = "EARLY_SINGLE_BAR_INCOMPLETE"
REASON_EARLY_PRICE = "EARLY_PRICE_NOT_CONTROLLED"
REASON_EARLY_VOLUME = "EARLY_VOLUME_NOT_MODERATE"
REASON_EARLY_FAM_SELL = "EARLY_DISTRIBUTION_ON_CONFIRMATION"
REASON_EARLY_BUY_READY = "EARLY_CONTROLLED_PROGRESS_MODERATE_VOLUME"
REASON_MANH_PRICE_NO_STRENGTHEN = "MANH_BREAK_PRICE_ABOVE_NO_STRENGTHEN"
REASON_MANH_STRENGTHEN_BELOW = "MANH_BREAK_STRENGTHEN_BELOW_REF"
REASON_MANH_BUY_READY = "MANH_BREAK_TWO_BAR_ABOVE_REF_PUBLISHED_STRENGTHEN"
REASON_MANH_PXV_WEAK = "MANH_BREAK_PXV_WEAK_ON_CONFIRMATION"
REASON_MANH_FAM_SELL = "MANH_BREAK_FAM_SELL_ON_CONFIRMATION"
REASON_CONFLICT = "CONFLICT_STRENGTH_AND_WEAK_OR_SELL"
REASON_WEAKENING = "WEAKENING_CONJUNCTION"
REASON_REF_UNUSABLE = "FROZEN_REF_UNUSABLE"
REASON_REF_UNIT_MISMATCH = "FROZEN_REF_UNIT_MISMATCH"
REASON_CHRONOLOGY_PRE_ELIGIBLE = "CHRONOLOGY_PRE_ELIGIBLE_BARS_IGNORED"
REASON_UNFINISHED = "UNFINISHED_5M_BAR_IGNORED"
REASON_DATE_ONLY = "DATE_ONLY_OR_MIDNIGHT_ILLEGAL"
REASON_RETROSPECTIVE = "RETROSPECTIVE_OVERLAY_NO_LIVE_BUY_READY"
REASON_SESSION_RESET = "SESSION_ROLLOVER_RESETS_ACTION_STATE"
REASON_WEAKENED_WAIT = "WEAKENED_MUST_PASS_WAIT"
REASON_MARKET_NOT_OK = "FROZEN_MARKET_PERMISSION_NOT_OK"
REASON_DATA_UNUSABLE = "DATA_GATE_UNUSABLE"
REASON_NOMINATED_NO_BARS = "NOMINATED_NO_LEGAL_COMPLETED_BARS"
REASON_WAIT = "WAIT_CONFIRMATION_INCOMPLETE"
REASON_UNKNOWN_SETUP = "UNKNOWN_SETUP_NO_BUY_READY"

# Research measurement. Not a production BUY state.
RESEARCH_DECISION_SHADOW_BUY = "SHADOW_BUY"
EXECUTION_ENABLED = False
REASON_NO_ORIGIN_SETUP = "NO_LEGITIMATE_ORIGIN_SETUP"
REASON_UNSUPPORTED_ORIGIN = "UNSUPPORTED_ORIGIN_SETUP"
REASON_MISSING_QUALIFIER = "MISSING_QUALIFIER"
REASON_MISSING_REFERENCE = "MISSING_DEFENSIBLE_REFERENCE"
REASON_INSUFFICIENT_BARS = "INSUFFICIENT_LEGAL_BARS"
REASON_WHEN_NOT_MET = "WHEN_NOT_MET"

SHADOW_BUY_READY_LABEL = "SHADOW BUY_READY (research only · not a production BUY)"
SHADOW_CAPTION = (
    "SHADOW / RESEARCH Action Layer · not a production BUY · "
    "candidate_is_buy=false · pxv_implies_buy=false · alert_eligible=false"
)

__all__ = [
    "ALERT_ELIGIBLE",
    "CANDIDATE_IS_BUY",
    "MODE",
    "OVERLAY_TRUTH_CANONICAL",
    "OVERLAY_TRUTH_RETROSPECTIVE",
    "PXV_IMPLIES_BUY",
    "REF_BREAKOUT",
    "REF_EMA9",
    "ROUTE_BREAK",
    "ROUTE_EARLY",
    "ROUTE_MANH",
    "ROUTE_PULL",
    "SCHEMA_EVIDENCE",
    "SCHEMA_STATE",
    "SHADOW_ACTION_STATES",
    "SHADOW_BUY_READY_LABEL",
    "SHADOW_CAPTION",
    "SLICE",
    "STATE_BUY_READY",
    "STATE_NOMINATED",
    "STATE_NO_OBSERVATION",
    "STATE_WAIT",
    "STATE_WEAKENED",
    "MARKET_PERMISSION_OK",
]
